-- <leader> key
vim.g.mapleader = " "

---@type dh.keymap.config
local config = {
	navigation = {
		-- This is overwritten by Oil if it is installed on the system
		file_explorer = { "<leader>nv" },
		oil = {
			action = { "<CR>" },
			action_split_vert = { "C-s" },
			action_split_hor = { "<C-h>" },
			close = { "<C-c>" },
			dir_cwd = { "_" },
			dir_up = { "-" },
			help = { "g?" },
			open_external = { "gx" },
			refresh = { "<C-r>" },
			toggle_preview = { "<C-p>" },
			toggle_hidden = { "g." },
			toggle_trash = { "g\\" },
		},
		window = {
			up = { "<Up>" },
			down = { "<Down>" },
			left = { "<Left>" },
			right = { "<Right>" },
			number_prefix = "<leader>",
		},
		auto_complete = {
			forward = { "<Tab>" },
			backward = { "<S-Tab>" },
			accept = { "<CR>" },
			close = { "<C-e>" },
			show = { "<C-space>" },
		},
		telescope = {
			find_files = { "<leader>nf" },
			find_references = { "F" },
			find_definitions = { "D" },
			find_type_definitions = { "<leader>D" },
			get_keymaps = { "<leader>hk" },
			git_branches = { "<leader>gb" },
			list_functions = { "<leader>fs" },
			list_symbols = { "<leader>ts" },
			grep_live = { "<leader>ns" },
			grep_selected = { "<leader>ns" },
		},
	},
	motions = {
		next_function = { "<C-j>" },
		prev_function = { "<C-k>" },
	},
	lsp = {
		find_references = { "F", disabled = true },
		goto_definition = { "D", disabled = true },
		goto_type_definition = { "T", disabled = true },
		goto_declaration = { "<leader>gd" },
		goto_implementation = { "I" },
		hover_info = { "K" },
		next_error = { "<C-j>", disabled = true },
		prev_error = { "<C-k>", disabled = true },
		rename = { "<F2>" },
		code_action = { "<leader>ca" },
		toggle_header = { "<leader>cc" },
	},
	debug = {
		restart = { "<shift><F5>", disabled = true },
		continue = { "<F5>", disabled = true },
		inspect = { "<leader>ds" },
		toggle_breakpoint = { "<leader>db" },
		toggle_breakpoint_cond = { "<leader>dc" },
		step_into = { "<F11>" },
		step_out = { "<F12>" },
		step_over = { "<F10>" },
	},
	tasks = {
		run = { "<F5>" },
		build = { "<F4>" },
		debug = { "<leader><F5>", disabled = true },
		debug_current = { "<leader><F5>" },
		set_build_type = { "<leader><F2>" },
	},
	overseer = {
		actions = { "<CR>" },
		open_float = { "<C-CR>" },
	},
	style = {
		toggle_colorizer = { "<leader>ct" },
	},
}

---@type dh.keymap.helper.keybind
local keybinds = require("keymap.helper.keybind")
local validation = {
	navigation = {
		file_explorer = keybinds.key,
		oil = {
			action = keybinds.key,
			action_split_vert = keybinds.key,
			action_split_hor = keybinds.key,
			close = keybinds.key,
			dir_cwd = keybinds.key,
			dir_up = keybinds.key,
			help = keybinds.key,
			open_external = keybinds.key,
			refresh = keybinds.key,
			toggle_preview = keybinds.key,
			toggle_hidden = keybinds.key,
			toggle_trash = keybinds.key,
		},
		window = {
			up = keybinds.key,
			down = keybinds.key,
			left = keybinds.key,
			right = keybinds.key,
		},
		auto_complete = {
			forward = keybinds.key,
			backward = keybinds.key,
			accept = keybinds.key,
			close = keybinds.key,
			show = keybinds.key,
		},
		telescope = {
			find_files = keybinds.key,
			find_references = keybinds.key,
			find_definitions = keybinds.key,
			find_type_definitions = keybinds.key,
			get_keymaps = keybinds.key,
			git_branches = keybinds.key,
			list_functions = keybinds.key,
			list_symbols = keybinds.key,
			grep_live = keybinds.key,
			grep_selected = keybinds.key,
		},
	},
	motions = {
		next_function = keybinds.key,
		prev_function = keybinds.key,
	},
	lsp = {
		find_references = keybinds.key,
		goto_definition = keybinds.key,
		goto_type_definition = keybinds.key,
		goto_declaration = keybinds.key,
		goto_implementation = keybinds.key,
		hover_info = keybinds.key,
		next_error = keybinds.key,
		prev_error = keybinds.key,
		rename = keybinds.key,
		code_action = keybinds.key,
		toggle_header = keybinds.key,
	},
	debug = {
		restart = keybinds.key,
		continue = keybinds.key,
		inspect = keybinds.key,
		toggle_breakpoint = keybinds.key,
		toggle_breakpoint_cond = keybinds.key,
		step_into = keybinds.key,
		step_out = keybinds.key,
		step_over = keybinds.key,
	},
	tasks = {
		build = keybinds.key,
		run = keybinds.key,
		debug = keybinds.key,
		debug_current = keybinds.key,
		set_build_type = keybinds.key,
	},
	overseer = {
		actions = keybinds.key,
		open_float = keybinds.key,
	},
	style = {
		toggle_colorizer = keybinds.key,
	},
}
return keybinds.parse(config, validation)
